### ISSUE TITLE
导入后出错

### ISSUE THREAD

**Issue by fl1tjo** [angmieee/tomato-mini-program#1]
![屏幕快照 2019-10-24 09 05 25](https://user-images.githubusercontent.com/36147624/67445589-07c1ec00-f640-11e9-8fbc-31c3cdae8056.png)

**Comment by NLxs** [comment]
没有app.js文件

**Comment by angmieee** [comment]
app.js 文件里有隐私信息，所以没有上传

NLxs <notifications@github.com> 于2019年10月26日周六 下午9:38写道：
